vaddatoyx      jmp addatoyx        ;l-math.asm
vanykey        jmp anykey          ;l-keyb.asm
vatohex        jmp atohex          ;l-conv.asm
vbmapclr       jmp bmapclr         ;l-bitmap.asm
vbmapinit      jmp bmapinit        ;l-bitmap.asm
vbmpfillbk     jmp bmpfillbk       ;l-bitmap.asm
vbytestohex    jmp bytestohex      ;l-conv.asm
vclrbasbuf     jmp clrbasbuf       ;l-float.asm
vclrkbbuf      jmp clrkbbuf        ;l-keyb.asm
vdbbline       jmp dbbline         ;l-drawbox.asm
vdbdraw        jmp dbdraw          ;l-drawbox.asm
vdbdrawline    jmp dbdrawline      ;l-drawbox.asm
vdbeline       jmp dbeline         ;l-drawbox.asm
vdbhline       jmp dbhline         ;l-drawbox.asm
vdbtline       jmp dbtline         ;l-drawbox.asm
vdecptr        jmp decptr          ;l-mem.asm
vdeczp1        jmp deczp1          ;l-mem.asm
vdeczp2        jmp deczp2          ;l-mem.asm
vdirectory     jmp directory       ;l-disk.asm
vdiskdir       jmp diskdir         ;l-disk.asm
vdiskerror     jmp diskerror       ;l-disk.asm
vdputsavemesg  jmp dputsavemesg    ;l-disk.asm
vdputsloadmesg jmp dputsloadmesg   ;l-disk.asm
vdrawbox       jmp drawbox         ;l-drawbox.asm
vdskerror      jmp dskerror        ;l-disk.asm
vfiletomem     jmp filetomem       ;l-disk.asm
vgetfac1       jmp getfac1         ;l-float.asm
vgetkey        jmp getkey          ;l-keyb.asm
vgotoxy        jmp gotoxy          ;l-string.asm
vincptr        jmp incptr          ;l-mem.asm
vincptr8       jmp incptr8         ;l-mem.asm
vinczp1        jmp inczp1          ;l-mem.asm
vinczp2        jmp inczp2          ;l-mem.asm
vkbfree        jmp kbfree          ;l-keyb.asm
vlsr4bits      jmp lsr4bits        ;l-conv.asm
vmemtofile     jmp memtofile       ;l-disk.asm
vnibtohex      jmp nibtohex        ;l-conv.asm
;vpetsciiaddr   jmp petsciiaddr     ;l-conv.asm
vpopall        jmp popall          ;l-push.asm
vpopregs       jmp popregs         ;l-push.asm
vprnfac1       jmp prnfac1         ;l-float.asm
vprnfac2       jmp prnfac2         ;l-float.asm
vptrtoyx       jmp ptrtoyx         ;l-mem.asm
vpushall       jmp pushall         ;l-push.asm
vpushregs      jmp pushregs        ;l-push.asm
vputahex       jmp putahex         ;l-conv.asm
vputahexdec    jmp putahexdec      ;l-string.asm
vputnch        jmp putnch          ;l-string.asm
vputs          jmp puts            ;l-string.asm
vputsc         jmp putsc           ;l-string.asm
vputscxy       jmp putscxy         ;l-string.asm
vputscyx       jmp putscyx         ;l-string.asm
vputsxy        jmp putsxy          ;l-string.asm
vputsyx        jmp putsyx          ;l-string.asm
vputyxhex      jmp putyxhex        ;l-conv.asm
vrolword       jmp rolword         ;l-math.asm
vrolzp1        jmp rolzp1          ;l-mem.asm
vrolzp2        jmp rolzp2          ;l-mem.asm
vrorzp1        jmp rorzp1          ;l-mem.asm
vrorzp2        jmp rorzp2          ;l-mem.asm
vscrnrest      jmp scrnrest        ;l-screen.asm     
vscrnsave      jmp scrnsave        ;l-screen.asm
vsetcarptr     jmp setcarptr       ;l-screen.asm
vsetcolptr     jmp setcolptr       ;l-screen.asm
vshowkey       jmp showkey         ;l-keyb.asm
vstrhexval     jmp strhexval       ;l-conv.asm
vstrlen        jmp strlen          ;l-string.asm
vsubatoyx      jmp subatoyx        ;l-math.asm
vwaitkey       jmp waitkey         ;l-keyb.asm
vwaitspace     jmp waitspace       ;l-keyb.asm
vwaitstop      jmp waitstop        ;l-keyb.asm
vyxtoptr       jmp yxtoptr         ;l-mem.asm
vzp1tozp2      jmp zp1tozp2        ;l-screen.asm
vzp2tozp1      jmp zp2tozp1        ;l-screen.asm
